name: zando
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  get_storage: ^2.0.2
  data_table_2: ^2.0.3
  percent_indicator: "^2.1.7+2"
  rounded_loading_button: ^2.0.3
  flutter_spinkit: any
  path_provider: ^2.0.6
  file_picker: ^4.3.3
  open_file: any
  timer_builder: ^2.0.0
  lottie: ^1.1.0
  printing: any
  image_picker: any
  mongo_dart: ^0.7.2
  flutter_svg: any
  page_transition: any
  sqlite3: ^1.5.1
  flutter_custom_clippers: ^2.0.0
  bubble_tab_indicator: "^0.1.5"
  expandable: ^5.0.1
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  desktop_window: ^0.4.0
  sqflite_common_ffi: any
  connectivity_plus: any
  google_fonts: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
